name: bolus
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - scikit-image
  - scikit-learn
  - matplotlib
  - opencv
  - jupyter
  - pytorch
  - pandas
  - tqdm
